providers = ["node"]

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "1"

[phases.install]
cmds = ["npm ci"]
cacheDirectories = []

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = []

[start]
cmd = "npm start"

[node]
version = "22.12"